### ISSUE TITLE
'mudraw' is now called 'mutool draw'

### ISSUE THREAD

**Issue by oimaasi** [uobikiemukot/idump#2]
In the helper script ipdf, the command 'mudraw' doesn't exist in the latest mupdf anymore. However,`mutool draw` doesn't seem to be a drop-in replacement for the old command. At least, I didn't succeed by simply substituting the command. 

According to the manpage of mutool, if `-o` is omitted, output will go to STDOUT. However, when I tried `mutool draw -F png $FILE $INDEX | idump -f`, idump complains about no input from STDIN.

I have to do something like this to get it work:

```
TMPF="/tmp/mupdf.png"
MUDRAW_OPT="-o $TMPF -F png -h 1024"
# ...
function show {
#"$FILE" to cope with white space in file name
mutool draw "$MUDRAW_OPT" "$FILE" $INDEX 2>/dev/null  
cat $TMPF | idump $IDUMP_OPT >/dev/null 2>&1
}
```

Explicitly writing to a tmp file should be unnecessary, but I can't figure out a way to just pipe them together. Any ideas? 

Moreover, do you know what the package of `mutool` is called in Arch Linux? I installed mupdf, it's not there. Then I added libmupdf, also no mutool. At last, I have to dig out my Gentoo machine and install mupdf, which does include mutool. A quick search of 'mutool arch linux' didn't give many helpful information either.

**Comment by uobikiemukot** [comment]
Thank you for your feedback.
I'll update ipdf script soon.

> Explicitly writing to a tmp file should be unnecessary, but I can't figure out a way to just pipe them together. Any ideas?

specify `/dev/stdout` as an output file like this:

~~~bash
...
FILE=$1
IDUMP_OPT="-f"
MUDRAW_OPT="-o /dev/stdout -F png -h 1024"

INDEX=1 # page origin:1
PAGES=`mutool info $FILE | grep "^Pages:" | cut -d" " -f2`

tput civis
#tput clear

#echo "filename:$FILE page:$INDEX"
mudraw $MUDRAW_OPT $FILE $INDEX 2> /dev/null | idump $IDUMP_OPT > /dev/null 2>&1
...
~~~

> Moreover, do you know what the package of mutool is called in Arch Linux? I installed mupdf, it's not there. Then I added libmupdf, also no mutool. At last, I have to dig out my Gentoo machine and install mupdf, which does include mutool. A quick search of 'mutool arch linux' didn't give many helpful information either.

mupdf-tools package includes "mutool" command.

- https://www.archlinux.org/packages/community/x86_64/mupdf-tools/

You can use pkgfile for searching package that includes required file.

- https://www.archlinux.org/packages/extra/x86_64/pkgfile/

**Comment by oimaasi** [comment]
Many thanks for the tips~!

> specify /dev/stdout as an output file like this

That was actually the first thing I tried, just following your original implementation. However, on one machine, the normal user got denied access to `stdout`:

```
error: cannot remove file '/dev/stdout': Permission denied
uncaught error: cannot remove file '/dev/stdout': Permission denied
```
I check `ls -la /dev/stdout`, which gives 

`lrwxrwxrwx 1 root root 15 Jan  1  1970 /dev/stdout -> /proc/self/fd/1
`

I know that in order to access `/dev/fb0`, user has to be in group `video`, but `stdout`? I don't understand. 

Furthermore, even if I switch to `root`, or on another machine where normal user has no problem accessing `stdout`, I still can't get it work

```
# mutool draw -o /dev/stdout -F png -h 1080 my.pdf 1 | idump -f

>>ERROR<<       stdin is empty
>>FATAL<<       input file not found

```

Am I missing something here?

**Comment by uobikiemukot** [comment]
> I know that in order to access /dev/fb0, user has to be in group video, but stdout? I don't understand.

You need to belong to `tty` group for /dev/stdout access.

~~~bash
$ ls -la /dev/stdout 
lrwxrwxrwx 1 root root 15 Mar 18 13:42 /dev/stdout -> /proc/self/fd/1
$ ls -la /proc/self/fd/1 
lrwx------ 1 haru users 64 May  8 09:23 /proc/self/fd/1 -> /dev/pts/0
$ ls -la /dev/pts/0 
crw--w---- 1 haru tty 136, 0 May  8 09:23 /dev/pts/0
~~~

> Furthermore, even if I switch to root, or on another machine where normal user has no problem accessing stdout, I still can't get it work

Hmm..., We may use "-" instead of "/dev/stdout"?

~~~bash
...
FILE=$1
IDUMP_OPT="-f"
MUDRAW_OPT="-o - -F png -h 1024"

INDEX=1 # page origin:1
PAGES=`mutool info $FILE | grep "^Pages:" | cut -d" " -f2`

tput civis

mudraw $MUDRAW_OPT $FILE $INDEX 2> /dev/null | idump $IDUMP_OPT > /dev/null 2>&1
...
~~~

**Comment by oimaasi** [comment]
> We may use "-" instead of "/dev/stdout"

Yes, that solves the problem. Thank you!
